version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: sh -c "make develop"
    ports:
      - "3000:3000"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
